stages:
  - buildlib

build-asi-dftbp:
  image: centos
  stage: buildlib
  script:
    - export CORES_NUMBER=`lscpu | awk -- '/Core\(s\) per socket/{C = $NF} /Socket/{S = $NF} END{print S*C}'`
    - echo $CORES_NUMBER
    - make -j $CORES_NUMBER

