stages:
  - buildlib
  - buildtests

build-asi-dftbp:
  image: registry.gitlab.com/pvst/asi/debian-dftbp
  stage: buildlib
  script:
    - export CORES_NUMBER=`lscpu | awk -- '/Core\(s\) per socket/{C = $NF} /Socket/{S = $NF} END{print S*C}'`
    - export INSTALL_PREFIX=install
    - make -j $CORES_NUMBER
    - make install
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - $INSTALL_PREFIX

build-asi-dftbp-tests:
  image: registry.gitlab.com/pvst/asi/debian-dftbp
  stage: buildtests
  script:
    - ls -lAhtr /root/opt/asi/include/
    - cd tests
    - export CORES_NUMBER=`lscpu | awk -- '/Core\(s\) per socket/{C = $NF} /Socket/{S = $NF} END{print S*C}'`
    - export ASI_HOME=install/
    - export DFTBP_LIB_DIR=${HOME}/opt/dftbp/lib
    - make -j $CORES_NUMBER

